// GENERATED by scripts/build-team-logos.mjs. Do not edit by hand.
// School name (CFBD) -> team id; files live at /logos/v2/<size>/<theme>/<id>.webp.
export const LOGO_IDS: Record<string, number> = {};
