"""Backward-compatible facade for preseason snapshots, features, and blends."""

from cks_picks_cfb.preseason_blends import (
    blend_early_season_predictions,
    evaluate_preseason_candidate,
    evaluate_preseason_predictions,
    fit_preseason_models,
    load_preseason_models,
    predict_preseason,
    preseason_blend_weight,
    save_preseason_models,
    select_blend_weights,
)
from cks_picks_cfb.preseason_features import (
    MATCHUP_CONTEXT_FEATURES,
    OPTIONAL_V4_SNAPSHOT_SOURCES,
    PRESEASON_FEATURES,
    PRIOR_QUALITY_FEATURES,
    REQUIRED_SNAPSHOT_SOURCES,
    SNAPSHOT_SCHEMA_VERSION,
    TEAM_FEATURES,
    V4_REQUIRED_SNAPSHOT_SOURCES,
    PreseasonSnapshotIngester,
    canonical_team,
    snapshot_is_complete,
    snapshot_sources_available,
    v4_preseason_feature_variants,
    v4_snapshot_is_usable,
    write_snapshot_source,
)
from cks_picks_cfb.preseason_matchups import build_preseason_matchups

__all__ = [
    "MATCHUP_CONTEXT_FEATURES",
    "OPTIONAL_V4_SNAPSHOT_SOURCES",
    "PRESEASON_FEATURES",
    "PRIOR_QUALITY_FEATURES",
    "REQUIRED_SNAPSHOT_SOURCES",
    "SNAPSHOT_SCHEMA_VERSION",
    "TEAM_FEATURES",
    "V4_REQUIRED_SNAPSHOT_SOURCES",
    "PreseasonSnapshotIngester",
    "blend_early_season_predictions",
    "build_preseason_matchups",
    "canonical_team",
    "evaluate_preseason_candidate",
    "evaluate_preseason_predictions",
    "fit_preseason_models",
    "load_preseason_models",
    "predict_preseason",
    "preseason_blend_weight",
    "save_preseason_models",
    "select_blend_weights",
    "snapshot_is_complete",
    "snapshot_sources_available",
    "v4_preseason_feature_variants",
    "v4_snapshot_is_usable",
    "write_snapshot_source",
]
