TEAM_LOGO_MAP = {
    "Sam Houston": "Sam Houston State",
    "UL Monroe": "Louisiana Monroe",
    "Massachusetts": "UMass",
    "App State": "Appalachian State",
    "San José State": "San Jose State",
    "UTSA": "UT San Antonio",
    "Hawai'i": "Hawai_i",
    "Hawaii": "Hawai_i",
    "Hawai i": "Hawai_i",
    "UConn": "Connecticut",
    "Southern Miss": "Southern Mississippi",
    "FIU": "Florida International",
    "Texas A&M": "Texas A&M",
}
